# Generated by Django 2.1.7 on 2019-08-03 09:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('browse', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderdetails',
            name='price_details',
        ),
        migrations.AddField(
            model_name='orderpricedetails',
            name='order',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='browse.OrderDetails'),
            preserve_default=False,
        ),
    ]
