# Generated by Django 2.1.7 on 2019-08-03 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('browse', '0002_auto_20190803_0907'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderpricedetails',
            name='subtotal_price',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='orderpricedetails',
            name='total_price',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='orderpricedetails',
            name='total_tax',
            field=models.CharField(max_length=100),
        ),
    ]
